---------------------tables constraints  
/*                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  ALTER TABLE NOTIF ADD FOREIGN KEY (ID_TAG)  REFERENCES TAG (ID_TAG) ENABLE;
  ALTER TABLE NOTIF ADD FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID_ETUDIANT) ENABLE;
  ALTER TABLE NOTIF ADD FOREIGN KEY (ID_MASTER) REFERENCES MASTER (ID_MASTER) ENABLE;
  ALTER TABLE PRESELECTION ADD FOREIGN KEY (ID_INSCRIPTION) REFERENCES INSCRIPTION (ID_INSCRIPTION) ENABLE;
  ALTER TABLE DOC ADD FOREIGN KEY (ID_MASTER) REFERENCES MASTER (ID_MASTER) ENABLE;
  ALTER TABLE DOC ADD FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID_ETUDIANT) ENABLE;
  ALTER TABLE FACULTE ADD FOREIGN KEY (ID_UNIVERSITE) REFERENCES UNIVERSITE (ID_UNIVERSITE) ENABLE;
  ALTER TABLE RESPONSABLE ADD FOREIGN KEY (ID_FACULTE)  REFERENCES FACULTE (ID_FACULTE) ENABLE;
  ALTER TABLE MASTER ADD FOREIGN KEY (ID_RESPONSABLE) REFERENCES RESPONSABLE (ID_RESPONSABLE) ENABLE;
  ALTER TABLE MASTER ADD FOREIGN KEY (ID_CONDITION) REFERENCES CONDITION (ID_CONDITION) ENABLE;
  ALTER TABLE FILIERE_ADMET_MASTER ADD FOREIGN KEY (ID_MASTER)  REFERENCES MASTER (ID_MASTER) ENABLE;
  ALTER TABLE FILIERE_ADMET_MASTER ADD FOREIGN KEY (ID_FIL_LICENCE) REFERENCES FILIERE_LICENCE (ID_FIL_LICENCE) ENABLE;
  ALTER TABLE INFO_ACADEMIQUE ADD FOREIGN KEY (ID_FIL_LICENCE)  REFERENCES FILIERE_LICENCE (ID_FIL_LICENCE) ENABLE;
  ALTER TABLE INFO_ACADEMIQUE ADD FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID_ETUDIANT) ENABLE;
  ALTER TABLE INFO_ACADEMIQUE ADD FOREIGN KEY (ID_FACULTE)  REFERENCES FACULTE (ID_FACULTE) ENABLE;
  ALTER TABLE INSCRIPTION ADD FOREIGN KEY (ID_MASTER) REFERENCES MASTER (ID_MASTER) ENABLE;
  ALTER TABLE INSCRIPTION ADD FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID_ETUDIANT) ENABLE;
*/

  -- ON DELETE CASCADE for foreign keys referencing the ETUDIANT table
ALTER TABLE NOTIF
ADD CONSTRAINT fk_notif_id_etudiant
FOREIGN KEY (ID_ETUDIANT)
REFERENCES ETUDIANT (ID_ETUDIANT)
ON DELETE CASCADE ENABLE;

ALTER TABLE DOC
ADD CONSTRAINT fk_doc_id_etudiant
FOREIGN KEY (ID_ETUDIANT)
REFERENCES ETUDIANT (ID_ETUDIANT)
ON DELETE CASCADE ENABLE;

ALTER TABLE INFO_ACADEMIQUE
ADD CONSTRAINT fk_info_academique_id_etudiant
FOREIGN KEY (ID_ETUDIANT)
REFERENCES ETUDIANT (ID_ETUDIANT)
ON DELETE CASCADE ENABLE;

ALTER TABLE INSCRIPTION
ADD CONSTRAINT fk_inscription_id_etudiant
FOREIGN KEY (ID_ETUDIANT)
REFERENCES ETUDIANT (ID_ETUDIANT)
ON DELETE CASCADE ENABLE;

-- ON DELETE SET NULL for other foreign keys
ALTER TABLE NOTIF
ADD CONSTRAINT fk_notif_id_tag
FOREIGN KEY (ID_TAG)
REFERENCES TAG (ID_TAG)
ON DELETE SET NULL ENABLE;

ALTER TABLE NOTIF
ADD CONSTRAINT fk_notif_id_master
FOREIGN KEY (ID_MASTER)
REFERENCES MASTER (ID_MASTER)
ON DELETE SET NULL ENABLE;

ALTER TABLE PRESELECTION
ADD CONSTRAINT fk_preselection_id_inscription
FOREIGN KEY (ID_INSCRIPTION)
REFERENCES INSCRIPTION (ID_INSCRIPTION)
ON DELETE SET NULL ENABLE;

ALTER TABLE DOC
ADD CONSTRAINT fk_doc_id_master
FOREIGN KEY (ID_MASTER)
REFERENCES MASTER (ID_MASTER)
ON DELETE SET NULL ENABLE;

ALTER TABLE FACULTE
ADD CONSTRAINT fk_faculte_id_universite
FOREIGN KEY (ID_UNIVERSITE)
REFERENCES UNIVERSITE (ID_UNIVERSITE)
ON DELETE SET NULL ENABLE;

ALTER TABLE RESPONSABLE
ADD CONSTRAINT fk_responsable_id_faculte
FOREIGN KEY (ID_FACULTE)
REFERENCES FACULTE (ID_FACULTE)
ON DELETE SET NULL ENABLE;

ALTER TABLE MASTER
ADD CONSTRAINT fk_master_id_responsable
FOREIGN KEY (ID_RESPONSABLE)
REFERENCES RESPONSABLE (ID_RESPONSABLE)
ON DELETE SET NULL ENABLE;

ALTER TABLE MASTER
ADD CONSTRAINT fk_master_id_condition
FOREIGN KEY (ID_CONDITION)
REFERENCES CONDITION (ID_CONDITION)
ON DELETE SET NULL ENABLE;

ALTER TABLE FILIERE_ADMET_MASTER
ADD CONSTRAINT fk_filiere_admet_master_id_master
FOREIGN KEY (ID_MASTER)
REFERENCES MASTER (ID_MASTER)
ON DELETE SET NULL ENABLE;

ALTER TABLE FILIERE_ADMET_MASTER
ADD CONSTRAINT fk_filiere_admet_master_id_fil_licence
FOREIGN KEY (ID_FIL_LICENCE)
REFERENCES FILIERE_LICENCE (ID_FIL_LICENCE)
ON DELETE SET NULL ENABLE;

ALTER TABLE INFO_ACADEMIQUE
ADD CONSTRAINT fk_info_academique_id_fil_licence
FOREIGN KEY (ID_FIL_LICENCE)
REFERENCES FILIERE_LICENCE (ID_FIL_LICENCE)
ON DELETE SET NULL ENABLE;

ALTER TABLE INFO_ACADEMIQUE
ADD CONSTRAINT fk_info_academique_id_faculte
FOREIGN KEY (ID_FACULTE)
REFERENCES FACULTE (ID_FACULTE)
ON DELETE SET NULL ENABLE;

ALTER TABLE INSCRIPTION
ADD CONSTRAINT fk_inscription_id_master
FOREIGN KEY (ID_MASTER)
REFERENCES MASTER (ID_MASTER)
ON DELETE SET NULL ENABLE;