--------------------------------------------------------
--  Fichier créé - lundi-octobre-14-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Trigger ADD_FAM
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."ADD_FAM" 
INSTEAD of insert on MASTER_FILIER_ADMET_V 
FOR EACH ROW 
begin 
    INSERT into FILIERE_ADMET_MASTER
    values (
            SQC_FILIERE_ADMET_MASTER.nextval,
            :NEW.ID_MASTER,
            :NEW.ID_FIL_LICENCE
            );
end;
/
ALTER TRIGGER "MEHDI"."ADD_FAM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADD_MASTER_CONDITION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."ADD_MASTER_CONDITION" INSTEAD of INSERT on MASTER_CONDITION_V
FOR EACH ROW
declare 
id_condition int;
BEGIN
    SELECT SQC_CONDITION.nextval INTO id_condition FROM dual;
    INSERT INTO condition values(
                                    id_condition,
                                    :NEW.MAX_AGE,
                                    :NEW.MAX_ANNEE_ETUDE,
                                    :NEW.NOTE_MIN_SEMESTRE,
                                    :NEW.NOTE_SEUIL
                                );
    INSERT INTO master values(
                                    :NEW.id_master,
                                    :NEW.SPECIALITE,
                                    upper(:NEW.NOM_COORDINATEUR),
                                    :NEW.D_DEBUT_INSCRIPTION,
                                    :NEW.D_FIN_INSCRIPTION,
                                    :NEW.D_AFF_PRESELECTION,
                                    :NEW.D_CONCOURS,
                                    :NEW.D_AFF_RESULTAT_CONCOURS,  
                                    :NEW.LIEU_CONCOURS,
                                    :NEW.INFORMATION,
                                    :NEW.ID_RESPONSABLE,
                                    id_condition,
                                    :NEW.DOCS_STRING,
                                    :NEW.CONDITION
                                );                                
END;
/
ALTER TRIGGER "MEHDI"."ADD_MASTER_CONDITION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ETUDIANT_INFO_INSERT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."ETUDIANT_INFO_INSERT_TRIGGER" 
INSTEAD OF INSERT ON Etudiant_Info_insertion                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
FOR EACH ROW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    v_id_etudiant INT;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    v_id_ia INT;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    -- Get next sequence value for ID_ETUDIANT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    SELECT SEQ_ETUDIANT.NEXTVAL INTO v_id_etudiant FROM DUAL;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

    -- Insert into Etudiant table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    INSERT INTO Etudiant (ID_ETUDIANT, NOM, PRENOM, D_NAISS, SEXE, TELE, EMAIL, PASSWORD, NATIONALITE, CIN, MASSAR)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    VALUES (v_id_etudiant, :NEW.NOM, :NEW.PRENOM, :NEW.D_NAISS, :NEW.SEXE, :NEW.TELE, :NEW.EMAIL, :NEW.PASSWORD, :NEW.NATIONALITE, :NEW.CIN, :NEW.MASSAR);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

    -- Get next sequence value for ID_IA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    SELECT SEQ_INFO_ACAD.NEXTVAL INTO v_id_ia FROM DUAL;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

    -- Insert into Info_academique table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    INSERT INTO Info_academique (ID_IA, D_LICENCE, D_BAC, FIL_BAC, MOY_LICENCE, MOY_BAC, N_S1, N_S2, N_S3, N_S4, N_S5, N_S6, PHOTO, ID_FIL_LICENCE, ID_ETUDIANT, ID_FACULTE,d_pr_inscription)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    VALUES (v_id_ia, :NEW.D_LICENCE, :NEW.D_BAC, :NEW.FIL_BAC, :NEW.MOY_LICENCE, :NEW.MOY_BAC, :NEW.N_S1, :NEW.N_S2, :NEW.N_S3, :NEW.N_S4, :NEW.N_S5, :NEW.N_S6, :NEW.PHOTO, :NEW.ID_FIL_LICENCE, v_id_etudiant, :NEW.ID_FACULTE, :NEW.d_pr_inscription);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

/
ALTER TRIGGER "MEHDI"."ETUDIANT_INFO_INSERT_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSCRIPTION_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."INSCRIPTION_TR" INSTEAD of INSERT on inscription_v                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
FOR Each row                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    INSERT into inscription(ID_INSCRIPTION, ID_MASTER, ID_ETUDIANT, d_inscription) VALUES(inscription_seq.NEXTVAL, :NEW.id_master, :NEW.id_Etudiant, sysdate);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

/
ALTER TRIGGER "MEHDI"."INSCRIPTION_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIF_CONV_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."NOTIF_CONV_TRIGGER" AFTER INSERT ON convocation
FOR EACH ROW
DECLARE
v_specialite VARCHAR2(60);
v_id_master number;
v_id_etudiant number;
BEGIN
    select id_master into v_id_master from inscription where id_Inscription = :NEW.id_Inscription;
    select id_etudiant into v_id_etudiant from inscription where id_Inscription = :NEW.id_Inscription;
    select specialite into v_specialite from master where id_master = v_id_master;
        INSERT INTO notif (id_notif, msg, notif_date, id_tag, readed, id_master, id_etudiant) 
        VALUES(notif_seq.NEXTVAL,
               'Felicitations ! Vous avez ete transfere de la liste d''attente a la liste finale pour pour le concours d''admission au master "' || v_specialite ||'". Veuillez consulter votre boîte mail pour plus d''informations.',
                sysdate,
                3,
                'f',
                v_id_master,
                v_id_etudiant);
END;
/
ALTER TRIGGER "MEHDI"."NOTIF_CONV_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIF_I_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."NOTIF_I_TRIGGER" AFTER INSERT ON inscription                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
FOR EACH ROW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
v_specialite VARCHAR2(60);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    select specialite into v_specialite from master where id_master = :NEW.id_master;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        INSERT INTO notif (id_notif, msg, notif_date, id_tag, readed, id_master, id_etudiant)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        VALUES(notif_seq.NEXTVAL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
               'Vous etes inscrit avec succes au master "' || v_specialite ||'".',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                sysdate,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                'f',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                :NEW.id_master,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                :NEW.id_etudiant);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

/
ALTER TRIGGER "MEHDI"."NOTIF_I_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIF_L_A_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."NOTIF_L_A_TRIGGER" AFTER INSERT ON Liste_Attente
FOR EACH ROW
DECLARE
v_specialite VARCHAR2(60);
v_id_master number;
v_id_etudiant number;
BEGIN
    select id_master into v_id_master from inscription where id_Inscription = :NEW.id_Inscription;
    select id_etudiant into v_id_etudiant from inscription where id_Inscription = :NEW.id_Inscription;
    select specialite into v_specialite from master where id_master = v_id_master;
        INSERT INTO notif (id_notif, msg, notif_date, id_tag, readed, id_master, id_etudiant) 
        VALUES(notif_seq.NEXTVAL,
               'Vous etes actuellement sur la liste d''attente pour le concours d''admission au master "' || v_specialite ||'".',
                sysdate,
                3,
                'f',
                v_id_master,
                v_id_etudiant);
END;

/
ALTER TRIGGER "MEHDI"."NOTIF_L_A_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIF_L_F_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."NOTIF_L_F_TRIGGER" AFTER INSERT ON Liste_Finale
FOR EACH ROW
DECLARE
v_specialite VARCHAR2(60);
v_id_master number;
v_id_etudiant number;
BEGIN
    select id_master into v_id_master from inscription where id_Inscription = :NEW.id_Inscription;
    select id_etudiant into v_id_etudiant from inscription where id_Inscription = :NEW.id_Inscription;
    select specialite into v_specialite from master where id_master = v_id_master;
        INSERT INTO notif (id_notif, msg, notif_date, id_tag, readed, id_master, id_etudiant) 
        VALUES(notif_seq.NEXTVAL,
               'Felicitations ! Vous etes sur la liste principale pour le concours d''admission au master "' || v_specialite ||'".',
                sysdate,
                3,
                'f',
                v_id_master,
                v_id_etudiant);
END;

/
ALTER TRIGGER "MEHDI"."NOTIF_L_F_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIF_P_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MEHDI"."NOTIF_P_TRIGGER" AFTER INSERT ON preselection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
FOR EACH ROW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
v_specialite VARCHAR2(60);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
v_id_master number;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
v_id_etudiant number;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    select id_master into v_id_master from inscription where id_Inscription = :NEW.id_Inscription;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    select id_etudiant into v_id_etudiant from inscription where id_Inscription = :NEW.id_Inscription;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    select specialite into v_specialite from master where id_master = v_id_master;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        INSERT INTO notif (id_notif, msg, notif_date, id_tag, readed, id_master, id_etudiant)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        VALUES(notif_seq.NEXTVAL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
               'Felicitations ! Vous avez ete preselectionne pour participer au concours d''admission au master "' || v_specialite ||'".',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                sysdate,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                'f',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                v_id_master,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                v_id_etudiant);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

/
ALTER TRIGGER "MEHDI"."NOTIF_P_TRIGGER" ENABLE;
